string filename                      # Name of bag file to save snapshot to.
                                     # if it ends in .bag, this exact filename will be saved.
                                     # otherwise, the current datetime and .bag will be appended to the name
                                     #   example: "test" -> test2018-05-23-10-04-20.bag
                                     #   example: "test.bag" -> test.bag
TopicDetails[] topics                # List of topics to include in snapshot.
                                     # If empty, all buffered topics will be written
builtin_interfaces/Time start_time   # Earliest timestamp for a message to be included in written bag
                                     # If time(0), start at the earliest message in each topic's buffer
builtin_interfaces/Time stop_time    # Latest timestamp for a message to be included in written bag
                                     # If time(0), stop at the most recent message in each topic's buffer
bool use_h264                        # If true, compress image topics using h264 encoding
bool throttle_msgs                   # If true, use the parameter of the topic to set the period of the messages
                                     # If false, include all messages in the time range
bool use_interval_mode               # If true, start_time and stop_time are interpreted as an interval around msg_timestamp
                                     # If false, start_time and stop_time are interpreted as absolute times
builtin_interfaces/Time  msg_timestamp  # Timestamp of the message that triggered the snapshot
                                        # that must be included. Helps in the interval_mode to avoid missing the message
float32 interval_mode_tolerance       # Tolerance in seconds for interval mode. If a message falls within the interval
                                     # [msg_timestamp - interval_mode_tolerance, msg_timestamp + interval_mode_tolerance]
                                     # it will be included in the snapshot
bool interval_mode_single_msg        # If true, only the message with timestamp msg_timestamp will be included in the snapshot
                                     # If false, all messages within the interval will be included         

---

bool success                         # True if snapshot successfully written to disk

string NO_DATA_MESSAGE=no messages buffered on selected topics
string message                       # Error description if failed
