/**:
  ros__parameters:
    topics: ["/points", "/odom", "/camera/image_raw"]
    topic_details:
      /points:
        type: "sensor_msgs/msg/PointCloud2"
      /odom:
        type: "nav_msgs/msg/Odometry"
        duration: 10.0
      /camera/image_raw:
        type: "sensor_msgs/msg/Image"
        duration: 15.0
        memory: 200000000.0  # bytes (200 MB); default_memory_limit is in MB
